#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page containing the string "Ceci n'est pas une page"

sudo apt-get update -y

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html

sudo sed -i '/server {/a \\t# Custom 404 error page\n\terror_page 404 /page_error_404.html;\n\tlocation = /page_error_404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart

