#!/usr/bin/env bash

# Configure Nginx to add a custom HTTP response header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"

sudo sed -i "/server {/a \\\t$HEADER" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html >> /dev/null
sudo sed -i "/server {/a \\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

STRING="location /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "/server {/a \\\t$STRING" /etc/nginx/sites-available/default

sudo service nginx restart

