#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install haproxy


echo '
frontend webridv.tech
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 554.197.45.152:80 check
    server web-02 54.162.100.252:80 check

' | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
